
dailymotion.api.base.url=https://api.dailymotion.com
spring.application.name=dailymotionminer
server.port=${PORT:8080}
videominer.base.url=${VIDEOMINER_URL:http://localhost:8080}
videominer.uri=${VIDEOMINER_URL:http://localhost:8080}/videominer/channels
videominer.api.key=${VIDEOMINER_API_KEY:1234}
